Fix multiple parameter values
jenkinsci/parameterized-scheduler-plugin pull request #20
Opened 2019-03-08 06:15 UTC by yogeshlonkar

getParameterValues should split value If parameter has multiple comma delimited values. below pattern fails in case of extended-choice-parameter-plugin
`H * * * * %param1=val1,abc,val3`
Check [createValue](https://github.com/jenkinsci/extended-choice-parameter-plugin/blob/7d1dfdb434cb0605e5d2000cbc6ca238b6a287d2/src/main/java/com/cwctravel/hudson/plugins/extended_choice_parameter/ExtendedChoiceParameterDefinition.java#L545) method in extended-choice-parameter-plugin

2019-08-29 20:27 UTC, batmat commented
I strongly suspect this could blow up is people are using it currently to pass sentences or so.
Wondering how to assess this and to accept this fix/evolution while preserving compatibility.

And I'd add a test to check this indeed.

Thanks!

2020-05-06 07:40 UTC, jankatins commented
I'm currently using it to pass multiple values via a single variable: `tasks=x,y,z`. This would break... IMO if you want to have it as an array, do the split in the pipeline itself?

2020-12-22 03:50 UTC, res0nance requested changes
From my understanding is this is unmergeable in its current state as it breaks backwards compatibility

2021-07-19 13:28 UTC, kklimek commented
Hi! I have issue somehow related to this PR.

I'm trying to schedule parametrized build with extendedChoice parameter:

```
                extendedChoice(
                        name: 'SAMPLE_CHOICE',
                        value: "d1,d2,d3",
                        visibleItemCount: 3,
                        multiSelectDelimiter: ',',
                        type: 'PT_CHECKBOX'
                )
```

I've tried many ways to add this to parametrized scheduler. It seems to work fine when I want to pass only one choice i.e:

`0 3 * * * % SAMPLE_CHOICE=d2`

However when I try to pass multiple values (and I've tried so many ways already) it ends up being empty i.e.:

`0 3 * * * % SAMPLE_CHOICE=d1,d2`
`0 3 * * * % SAMPLE_CHOICE=\"d1\",\"d2\"`
`0 3 * * * % SAMPLE_CHOICE=[d1,d2]`

And so on...

Is there any way to schedule multiple values without this change?

2021-07-20 12:08 UTC, kklimek commented
Also I have an idea - maybe there should be clear indicator that variable is an array i.e.:

`0 3 * * * % SAMPLE_CHOICE[]=d1,d2`

2021-07-20 14:57 UTC, res0nance commented
> Hi! I have issue somehow related to this PR.
> 
> I'm trying to schedule parametrized build with extendedChoice parameter:
> 
> ```
>                 extendedChoice(
>                         name: 'SAMPLE_CHOICE',
>                         value: "d1,d2,d3",
>                         visibleItemCount: 3,
>                         multiSelectDelimiter: ',',
>                         type: 'PT_CHECKBOX'
>                 )
> ```
> 
> I've tried many ways to add this to parametrized scheduler. It seems to work fine when I want to pass only one choice i.e:
> 
> `0 3 * * * % SAMPLE_CHOICE=d2`
> 
> However when I try to pass multiple values (and I've tried so many ways already) it ends up being empty i.e.:
> 
> `0 3 * * * % SAMPLE_CHOICE=d1,d2`
> `0 3 * * * % SAMPLE_CHOICE=\"d1\",\"d2\"`
> `0 3 * * * % SAMPLE_CHOICE=[d1,d2]`
> 
> And so on...
> 
> Is there any way to schedule multiple values without this change?

As of right now there is no way to support this

2021-08-01 17:15 UTC, closed without merging

2022-06-15 16:07 UTC, dreps350 commented
> Hi! I have issue somehow related to this PR.
> 
> I'm trying to schedule parametrized build with extendedChoice parameter:
> 
> ```
>                 extendedChoice(
>                         name: 'SAMPLE_CHOICE',
>                         value: "d1,d2,d3",
>                         visibleItemCount: 3,
>                         multiSelectDelimiter: ',',
>                         type: 'PT_CHECKBOX'
>                 )
> ```
> 
> I've tried many ways to add this to parametrized scheduler. It seems to work fine when I want to pass only one choice i.e:
> 
> `0 3 * * * % SAMPLE_CHOICE=d2`
> 
> However when I try to pass multiple values (and I've tried so many ways already) it ends up being empty i.e.:
> 
> `0 3 * * * % SAMPLE_CHOICE=d1,d2` `0 3 * * * % SAMPLE_CHOICE=\"d1\",\"d2\"` `0 3 * * * % SAMPLE_CHOICE=[d1,d2]`
> 
> And so on...
> 
> Is there any way to schedule multiple values without this change?

Hi, did you find any workaround?