Fix - Concurrent jobs launch: start several cron expressions at the same time
jenkinsci/parameterized-scheduler-plugin pull request #44
Opened 2019-10-07 18:31 UTC by yevhen-hryhorevskyi

Hi there,

I liked the plugin and idea of setting up multiple cron expressions with different parameters. I looked through readme and found an image where two jobs (#18, #19) were launched at the same time. That was exactly what I needed.

But, unfortunately, I was not able to setup configuration to run different periodical cron expressions at the same time.
Digging into the code, I realized that this plugin worked differently:
- It runs a check every minute to launch a cron task with specific parameters.
- It makes a lookup only for the first cron expression that should start at that moment.

Based on the documentation and real implementation, I concluded that there was a bug in code, or it was the desired behavior and misleading documentation.

2020-07-17 18:28 UTC, danielfariati commented
I'm having the exact same issue described / solved in this pull-request.
It would be awesome if someone can merge this.

2020-09-07 07:54 UTC, carlosaya commented
same problem here!  can this pull request get some love?   🙏

2020-09-08 10:52 UTC, wy-z commented
I'm having the same issue too, hope this PR can be merged.

2020-09-24 23:47 UTC, BenCamareno commented
Same issue as described, please merge

2020-11-10 09:14 UTC, batmat commented
Hi everyone,

I'm the current maintainer of this plugin. TBH with myself, I lack the time to maintain this plugin, so if somebody can take over the maintenance, I'll be happy to hand it over.

Process: https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

Thanks!

2020-12-22 04:21 UTC, res0nance requested changes

2020-12-22 04:21 UTC, res0nance commented on src/test/java/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedCronTabListTest.java
> -		ParameterizedCronTabList testObject = ParameterizedCronTabList.create("* * * * *%foo=bar");
This second test should be split into a new test

2021-01-01 05:30 UTC, res0nance commented
@yevhen-hryhorevskyi are you still interested in this PR?

2021-01-04 22:52 UTC, yevhen-hryhorevskyi commented
@res0nance Considering the number of comments to merge this PR, yes I'm still interested in it. Let me take care of the comments & merge conflicts later today

2021-03-11 05:16 UTC, res0nance commented
> @res0nance Considering the number of comments to merge this PR, yes I'm still interested in it. Let me take care of the comments & merge conflicts later today

Do you have time to still work on this? Would you like me to continue with this?

2021-04-28 10:30 UTC, chunming08 commented
> > @res0nance Considering the number of comments to merge this PR, yes I'm still interested in it. Let me take care of the comments & merge conflicts later today
> 
> Do you have time to still work on this? Would you like me to continue with this?

@res0nance , can you please kindly share the schedule of the next release of this plugin? It's been 4 months since last and I am still waiting for the functionality that this PR provides - https://github.com/jenkinsci/parameterized-scheduler-plugin/pull/47

2021-04-28 11:10 UTC, res0nance commented
> > > @res0nance Considering the number of comments to merge this PR, yes I'm still interested in it. Let me take care of the comments & merge conflicts later today
> > 
> > 
> > Do you have time to still work on this? Would you like me to continue with this?
> 
> @res0nance , can you please kindly share the schedule of the next release of this plugin? It's been 4 months since last and I am still waiting for the functionality that this PR provides - #47

Probably releasing this today because i just wrote PR #105 to supersede this. Once merged there shouldn't be anything else outstanding.

2021-04-28 11:10 UTC, closed without merging